name: tunnel-rats-plugin
main: tunnel_rats.TunnelRats
version: 0.1.0
description: Inspired by Xisuma's Tunnel Rats game on Hermitcraft!
author: Ninjaking312
api-version: '1.20'
depend: [WorldEdit]
commands:
  tunnel:
    description: Load or list tunnels
    usage: /tunnel <name> to generate the specified tunnel, /tunnel to list all tunnels.
    permission: op
    permission-message: You do not have permission to run this command!
permissions:
  op:
    default: op
